
Config = {}
Config.Clues = {
    
    ["itinerary"] = {
        description = 'A Strange Sign',
        model = 'prop_afsign_amun',
        icon = 'fa fa-map-signs',
        location = vector4(-511.72, -256.16, 34.50, 100.9),
        configItem = {
            ["name"] = "itinerary", 			
            ["label"] = "Itinerary", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "itinerary.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A paint splattered itinerary"},					

    },
    ["paintShop"] = {
        description = 'A Curious Model Rocket',
        model = 'ind_prop_firework_01',
        icon = 'fa-solid fa-rocket',
        location = vector4(1646.02, 4839.92, 41.03, 88.35),
        configItem = {
            ["name"] = "rocketship", 			
            ["label"] = "Rocket Ship", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "rocketShip.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A Curious Rocket Ship with a torn logo on it."},					

    },
    ["upAndAtom"] = {
        description = 'A Mysterious Briefcase',
        model = 'prop_idol_case',
        challenge = 'circle',
        icon = 'fa-solid fa-briefcase',
        location = vector4(-1555.82, -464.4, 34.88, 19.10),
        configItem = {
            ["name"] = "ingridnote", 			
            ["label"] = "A note about Ingrid", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "ingridnote.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "\"Going to see Ingrid, she always liked to hang out with those greasy types\""},					

    },
    ["yellowJack"] = {
        description = 'An out of place notebook',
        model = 'v_med_p_notebook',
        icon = 'fa-solid fa-book',
        location = vector4(1982.49, 3050.45, 46.22, 0),
        configItem = {
            ["name"] = "receipt", 			
            ["label"] = "A Stained Receipt", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "receipt.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A stained receipt from the Yellow Jack"},					

    },
    ["greatOcean"] = {
        description = 'A Dirty Briefcase',
        model = 'prop_idol_case',
        challenge = 'thermite',
        icon = 'fa-solid fa-wine-bottle',
        location = vector4(-2955.68, 381.49, 14.21, 0),
        configItem = {
            ["name"] = "magiclamp", 			
            ["label"] = "Genie Lamp With Tag", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "magiclamp.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "M.P.B. | YORK"},					

    },
    ["alladinsCave"] = {
        description = 'A Fish Cooler',
        model = 'v_ret_fh_coolbox',
        icon = 'fa-solid fa-fish',
        location = vector4(800.21, -92.68, 85.45, 0),
        configItem = {
            ["name"] = "fishmenu", 			
            ["label"] = "A Torn Menu", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "fishmenu.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A torn menu. Smells of Salt"},					

    },
    ["hokies"] = {
        description = 'A Bouquet of Flowers',
        model = 'prop_snow_flower_02',
        icon = 'fa-solid fa-gift',
        location = vector4(-2187.49, 4249.22, 47.94, 0),
        configItem = {
            ["name"] = "stacybouquet", 			
            ["label"] = "Bouquet of Flowers", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "stacybouquet.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A Bouquet of flowers with the name \"Stacy\" written on it"},					

    },
    ["stacys"] = {
        description = 'Another Mystery Briefcase',
        model = 'prop_ld_case_01_s',
        icon = 'fa-solid fa-box',
        challenge = 'circle',
        location = vector4(-1474.28, -388.43, 44.49, 0),
        configItem = {
            ["name"] = "dungeoncard", 			
            ["label"] = "Mysterious Handoud", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "dungeoncard.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A blue card with the number 8852 written on it"},					

    },
    ["theDungeon"] = {
        description = 'A Moldy Taco',
        model = 'prop_taco_02',
        icon = 'fa-solid fa-utensils',
        location = vector4(-277.95, 194.58, 86.01, 0),
        configItem = {
            ["name"] = "tacowrapper", 			
            ["label"] = "Taco Wrapper", 		
            ["weight"] = 100, 		
            ["type"] = "item", 		
            ["image"] = "tacowrapper.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A torn taco wrapper with the words \"Famous Tacos\" written on it"},					

    },

    --Phase 2 Clues
    ["Yacht"] = {
        description = 'You find something in the trash...',
        model = 'v_ret_csr_bin',
        icon = 'far fa-file-alt',
        location = vector4(-1394.75, 6749.47, 7.97, 146.11),
        configItem = {
            ["name"] = "threatening_letter", 			
            ["label"] = "A Letter", 		
            ["weight"] = 10, 		
            ["type"] = "item", 		
            ["image"] = "threatening_letter.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A Threatening Letter"},					

    },

    ["LaFuenteBlancaNote"] = {
        description = 'You find something in the trash...',
        model = 'v_ret_csr_bin',
        icon = 'far fa-file-alt',
        location = vector4(1489.21, 1130.44, 113.34, 37.78),
        configItem = {
            ["name"] = "benedict_note", 			
            ["label"] = "A Note from Benedict", 		
            ["weight"] = 10, 		
            ["type"] = "item", 		
            ["image"] = "benedict_note.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "A note left behind by Benedict"},
    },
    ["LaFuenteBlancaKeys"] = {
        description = 'Set of Keys',
        model = 'v_ind_cs_toolbox1',
        icon = 'far fa-file-alt',
        location = vector4(1489.06, 1128.49, 114.13, 72.85),
        configItem = {		
            ["name"] = "setofkeys", 			
            ["label"] = "A set of 3 different keys", 		
            ["weight"] = 10, 		
            ["type"] = "item", 		
            ["image"] = "setofkeys.png", 	
            ["unique"] = true, 		
            ["useable"] = true, 	
            ["shouldClose"] = true,	   
            ["combinable"] = nil,   
            ["description"] = "What do these open?"},			
        },

  ["TrevorsTrailerPliers"] =  {
        description = 'A Locked Toolbox',
        model = 'v_ind_cs_toolbox4',
        challenge = 'circle2',
        icon = 'fas fa-lock',
        location =vector4(1974.73, 3827.74, 31.35, 219.16),
        configItem = {
                ["name"] = "pliers", 			
                ["label"] = "Pliers", 		
                ["weight"] = 50, 		
                ["type"] = "item", 		
                ["image"] = "pliers.png", 	
                ["unique"] = true, 		
                ["useable"] = true, 	
                ["shouldClose"] = true,	   
                ["combinable"] = nil,   
                ["description"] = "Pliers"},
        },

    ["TrevorsTrailerDrill"] =  {
        description = 'A Locked Toolbox',
        model = 'v_ind_cs_toolbox4',
        challenge = 'circle2',
        icon = 'fas fa-lock',
        location = vector4(1980.76, 3819.38, 31.43, 288.79),
        configItem = {
                ["name"] = "powerdrill", 			
                ["label"] = "A Power Drill", 		
                ["weight"] = 50, 		
                ["type"] = "item", 		
                ["image"] = "powerdrill.png", 	
                ["unique"] = true, 		
                ["useable"] = true, 	
                ["shouldClose"] = true,	   
                ["combinable"] = nil,   
                ["description"] = "A Power Drill"},
        },

    ["TrevorsTrailerBattery"] =  {
        description = 'A Locked Toolbox',
        model = 'v_ind_cs_toolbox4',
        challenge = 'circle2',
        icon = 'fas fa-lock',
        location = vector4(1962.36, 3812.22, 31.4, 80.9),    
        configItem = {
                ["name"] = "car_battery", 			
                ["label"] = "Car Batter", 		
                ["weight"] = 50, 		
                ["type"] = "item", 		
                ["image"] = "car_battery.png", 	
                ["unique"] = true, 		
                ["useable"] = true, 	
                ["shouldClose"] = true,	   
                ["combinable"] = nil,   
                ["description"] = "A Car Battery"},
        },

    ["TrevorsTrailerNote"] =  {
        description = 'A Bloody Note',
        model = 'ch_prop_collectibles_garbage_01a',
        icon = 'far fa-file-alt',
        location = vector4(1988.75, 3821.72, 31.3, 93.2),
        configItem = {
                ["name"] = "bloddy_note", 			
                ["label"] = "A Bloody Note", 		
                ["weight"] = 5, 		
                ["type"] = "item", 		
                ["image"] = "bloody_note.png", 	
                ["unique"] = true, 		
                ["useable"] = true, 	
                ["shouldClose"] = true,	   
                ["combinable"] = nil,   
                ["description"] = "A small note with some blood splatter"},
        },

        ["TortureRoomLaptop"] = {
            description = 'A Password Protected Laptop',
            model = 'p_cs_laptop_02',
            challenge = 'password1',
            icon = 'fas fa-user-lock',
            location = vector4(152.26, -2204.63, 4.19, 218.44),
            configItem = {
                ["name"] = "small_note", 			
                ["label"] = "A small note", 		
                ["weight"] = 10, 		
                ["type"] = "item", 		
                ["image"] = "small_note.png", 	
                ["unique"] = true, 		
                ["useable"] = true, 	
                ["shouldClose"] = true,	   
                ["combinable"] = nil,   
                ["description"] = "Durex mum pile"},
        },

        ["TortureRoomNote"] = {
            description = 'You notice an oddly colored post-it note',
            model = 'v_res_paperfolders',
            icon = 'fas fa-search',
            location = vector4(140.16, -2202.07, 3.69, 298.52),
            configItem = {
                ["name"] = "postitnote", 			
                ["label"] = "A Strange Post-it Note", 		
                ["weight"] = 10, 		
                ["type"] = "item", 		
                ["image"] = "postitnote.png", 	
                ["unique"] = true, 		
                ["useable"] = true, 	
                ["shouldClose"] = true,	   
                ["combinable"] = nil,   
                ["description"] = "A strange Post-it Note"},					
        },    

        ["CoronersOffice"] = {
            description = 'A Password protected Computer',
            model = 'p_cs_laptop_02',
            challenge = 'password2',
            icon = 'fas fa-user-secret',
            location = vector4(232.35, -1369.36, 39.43, 55.7),
            configItem = {
                ["name"] = "noteandflowers", 			
                ["label"] = "A Note and Flowers", 		
                ["weight"] = 10, 		
                ["type"] = "item", 		
                ["image"] = "noteandflowers.png", 	
                ["unique"] = true, 		
                ["useable"] = true, 	
                ["shouldClose"] = true,	   
                ["combinable"] = nil,   
                ["description"] = "A note from Benedict with flowers"},
        },           
}
